/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#bec6e0",
        "surface-dim": "#131315",
        "secondary-fixed": "#d5e3fd",
        "tertiary-container": "#231500",
        "surface-tint": "#bec6e0",
        "error": "#ffb4ab",
        "on-primary-container": "#798098",
        "surface-container": "#1f1f21",
        "on-secondary-fixed-variant": "#3a485c",
        "primary-container": "#0f172a",
        "surface-container-high": "#2a2a2b",
        "on-background": "#e4e2e4",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#957d5a",
        "secondary": "#b9c7e0",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#271901",
        "background": "#131315",
        "surface-bright": "#39393b",
        "surface-variant": "#353436",
        "surface-container-highest": "#353436",
        "secondary-fixed-dim": "#b9c7e0",
        "secondary-container": "#3c4a5e",
        "surface-container-low": "#1b1b1d",
        "on-secondary-fixed": "#0d1c2f",
        "on-secondary-container": "#abb9d2",
        "surface": "#131315",
        "on-tertiary-fixed-variant": "#574425",
        "on-surface": "#e4e2e4",
        "on-secondary": "#233144",
        "tertiary-fixed": "#fcdeb5",
        "inverse-on-surface": "#303032",
        "primary-fixed": "#dae2fd",
        "outline-variant": "#45464d",
        "on-surface-variant": "#c6c6cd",
        "surface-container-lowest": "#0e0e10",
        "outline": "#909097",
        "tertiary": "#dec29a",
        "error-container": "#93000a",
        "inverse-surface": "#e4e2e4",
        "inverse-primary": "#565e74",
        "on-error": "#690005",
        "on-primary-fixed": "#131b2e",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#dec29a",
        "on-primary": "#283044",
        "on-tertiary": "#3e2d11",
        "tech-blue": "#3B82F6",
        "tech-slate": "#334155",
        "tech-emerald": "#10B981"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1440px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
